# gRPC Dockerfile
FROM python:3.10

ENV PYTHONPATH /app
COPY requirements.txt .
RUN /usr/local/bin/python -m pip install --upgrade setuptools===58.0.0
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "grpc_server.py"]