version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://fserrano:F3rn4nd0!!@db:5432/appdb
      - JWT_SECRET=pandatech-jwt-secret
    volumes:
      - .:/app

  grpc:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    ports:
      - "50051:50051"
    depends_on:
      - db
      - proto-gen
    environment:
      - DATABASE_URL=postgresql://fserrano:F3rn4nd0!!@db:5432/appdb
      - JWT_SECRET=pandatech-jwt-secret
    volumes:
      - .:/app

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=fserrano
      - POSTGRES_PASSWORD=F3rn4nd0!!
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"

  proto-gen:
    build: .
    command: python generate_protos.py
    volumes:
      - .:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - fastapi

volumes:
  postgres_data: