# Docker Compose configuration

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://fserrano:F3rn4nd0!!@db:5432/appdb
      - JWT_SECRET=pandatech-jwt-secret
    volumes:
      - ./app:/app
      - /Users/fserrano/Desktop/:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  grpc:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    ports:
      - "50051:50051"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://fserrano:F3rn4nd0!!@db:5432/appdb
      - JWT_SECRET=pandatech-jwt-secret
    volumes:
      - ./app:/app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=fserrano
      - POSTGRES_PASSWORD=F3rn4nd0!!
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - fastapi
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  postgres_data: